spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/banco_marketplace
spring.datasource.username=springuser
spring.datasource.password=springpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR

server.port=8080
server.address=0.0.0.0

# SMTP BREVO API 
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=9cdd6d001@smtp-brevo.com
spring.mail.password=${SMTP_PASSWORD}
spring.mail.from=mercadoacademico@outlook.pt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# STRIPE API 

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
